#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Iterate through subdirectories of the project
for dir in */; do
    package_json="$dir/package.json"
    if test -f "$package_json" && grep -q '"slidev":' "$package_json"; then
        cd "$dir"
        npm run build
        mv dist/* ~/Projects/clmay.github.io/talks/"$dir"
        rm -rf dist
        cd ..
    fi
done
